/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WardenIndexRouteImport } from './routes/warden.index'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as SecurityIndexRouteImport } from './routes/security.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentNewRouteImport } from './routes/student.new'
import { Route as AdminExportRouteImport } from './routes/admin.export'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WardenIndexRoute = WardenIndexRouteImport.update({
  id: '/warden/',
  path: '/warden/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentNewRoute = StudentNewRouteImport.update({
  id: '/student/new',
  path: '/student/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/admin/export',
  path: '/admin/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/export': typeof AdminExportRoute
  '/student/new': typeof StudentNewRoute
  '/admin/': typeof AdminIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/student/': typeof StudentIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/warden/': typeof WardenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/export': typeof AdminExportRoute
  '/student/new': typeof StudentNewRoute
  '/admin': typeof AdminIndexRoute
  '/security': typeof SecurityIndexRoute
  '/student': typeof StudentIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/warden': typeof WardenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/export': typeof AdminExportRoute
  '/student/new': typeof StudentNewRoute
  '/admin/': typeof AdminIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/student/': typeof StudentIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/warden/': typeof WardenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/export'
    | '/student/new'
    | '/admin/'
    | '/security/'
    | '/student/'
    | '/verify/'
    | '/warden/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/export'
    | '/student/new'
    | '/admin'
    | '/security'
    | '/student'
    | '/verify'
    | '/warden'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/export'
    | '/student/new'
    | '/admin/'
    | '/security/'
    | '/student/'
    | '/verify/'
    | '/warden/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminExportRoute: typeof AdminExportRoute
  StudentNewRoute: typeof StudentNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
  WardenIndexRoute: typeof WardenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warden/': {
      id: '/warden/'
      path: '/warden'
      fullPath: '/warden/'
      preLoaderRoute: typeof WardenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/new': {
      id: '/student/new'
      path: '/student/new'
      fullPath: '/student/new'
      preLoaderRoute: typeof StudentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/admin/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminExportRoute: AdminExportRoute,
  StudentNewRoute: StudentNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  SecurityIndexRoute: SecurityIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
  WardenIndexRoute: WardenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
