// verify.index.tsx
// FIXED: Backend ne /api/verify/{token} mein exp aur sig mandatory kar diya.
// Is page pe manual token lookup tha bina signature ke — ab 400 aata hai.
// Fix: Manual lookup ko clearly "read-only preview" ke roop mein explain karo,
// aur 400 ka proper message dikhao. Actual scan security.index.tsx pe camera se hoga.

import { createFileRoute } from "@tanstack/react-router";
import { ProtectedRoute } from "@/components/ProtectedRoute";
import { DashboardShell } from "@/components/DashboardShell";
import { useState } from "react";
import { api } from "@/lib/api";
import type { GatePass } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Loader2, Search, Info } from "lucide-react";
import toast from "react-hot-toast";
import { StatusBadge } from "@/components/StatusBadge";
import { format } from "date-fns";
import { getErrorMessage } from "@/components/AsyncState";

export const Route = createFileRoute("/verify/")({
  component: () => (
    <ProtectedRoute roles={["SECURITY", "ADMIN", "WARDEN"]}>
      <Verify />
    </ProtectedRoute>
  ),
});

function Verify() {
  const [token, setToken] = useState("");
  const [busy, setBusy] = useState(false);
  const [pass, setPass] = useState<GatePass | null>(null);
  const [sigError, setSigError] = useState(false);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    const trimmed = token.trim();
    if (!trimmed || busy) return;

    setBusy(true);
    setPass(null);
    setSigError(false);

    try {
      // NOTE: /api/verify/{token} ab exp aur sig query params require karta hai.
      // Yeh page sirf QR-scanned URL se aane pe properly kaam karega jisme
      // signed URL hoga. Manual token lookup ke liye security guard ko
      // camera scan use karna chahiye (Gate Scan page).
      const data = await api<GatePass>(
        `/api/verify/${encodeURIComponent(trimmed)}`,
      );
      setPass(data);
    } catch (e) {
      const msg = getErrorMessage(e, "Pass not found");
      // 400 = signature missing/invalid (expected after backend fix)
      if (/400|exp|sig|signature|expired link/i.test(msg)) {
        setSigError(true);
      } else {
        toast.error(msg);
      }
    } finally {
      setBusy(false);
    }
  };

  return (
    <DashboardShell title="Verify Pass" subtitle="Look up a pass by QR token">
      <div className="mx-auto max-w-2xl space-y-6">

        {/* Info banner explaining signature requirement */}
        <div className="flex items-start gap-3 rounded-xl border border-primary/30 bg-primary/5 p-4 text-sm">
          <Info className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
          <div>
            <p className="font-medium text-foreground">QR scan recommended</p>
            <p className="mt-0.5 text-muted-foreground">
              For security, QR verification requires a valid signed URL (generated by
              the student's app). Manual token lookup only works if you paste the
              complete signed URL or use the{" "}
              <a href="/security" className="text-primary underline underline-offset-2">
                Gate Scan
              </a>{" "}
              page's camera.
            </p>
          </div>
        </div>

        <Card className="glass border-border/60">
          <CardContent className="p-6">
            <form onSubmit={submit} className="flex gap-2">
              <Input
                value={token}
                onChange={(e) => { setToken(e.target.value); setSigError(false); }}
                placeholder="Paste QR token or signed URL..."
                className="h-11"
              />
              <Button disabled={busy} type="submit">
                {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}
              </Button>
            </form>

            {/* Signature error — clear, actionable message */}
            {sigError && (
              <div className="mt-4 rounded-lg border border-warning/40 bg-warning/10 p-3 text-sm">
                <p className="font-medium text-warning">Signature verification required</p>
                <p className="mt-0.5 text-muted-foreground">
                  This token cannot be verified without a valid signature. Ask the
                  student to open their pass and show the QR code, then use the{" "}
                  <a href="/security" className="text-primary underline underline-offset-2">
                    Gate Scan
                  </a>{" "}
                  camera to scan it.
                </p>
              </div>
            )}
          </CardContent>
        </Card>

        {pass && (
          <Card className="glass border-border/60">
            <CardContent className="p-6">
              <div className="mb-4 flex flex-wrap items-center justify-between gap-2">
                <div>
                  <div className="text-xs text-muted-foreground">Verified</div>
                  <div className="text-lg font-semibold">{pass.studentName ?? "Unknown"}</div>
                  <div className="text-xs text-muted-foreground">ID #{pass.studentId ?? "N/A"}</div>
                </div>
                <StatusBadge status={pass.status} />
              </div>
              <dl className="grid gap-2 text-sm">
                <Row label="Reason" value={pass.reason ?? "N/A"} />
                <Row label="Destination" value={pass.destination ?? "N/A"} />
                <Row label="Student Mobile" value={pass.studentMobile ?? "—"} />
                <Row label="Parent Mobile" value={pass.parentMobile ?? "—"} />
                <Row label="Leave" value={pass.leaveAt ? format(new Date(pass.leaveAt), "PPp") : "N/A"} />
                <Row label="Return by" value={pass.returnBy ? format(new Date(pass.returnBy), "PPp") : "N/A"} />
              </dl>
            </CardContent>
          </Card>
        )}
      </div>
    </DashboardShell>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-start justify-between gap-4 border-b border-border/40 py-1.5 last:border-0">
      <span className="text-muted-foreground">{label}</span>
      <span className="text-right font-medium">{value}</span>
    </div>
  );
}